% This scripts compiles the FCD maps project for Windows.
% For more information about mcc function, check: https://www.mathworks.com/help/mps/ml_code/mcc.html

clear; clc; oldpath = path; tic;
fprintf('[INFO] Starting compilation\n');
compile_dir = fullfile('.','compiled',strcat('SegmentGM_',datestr(datetime("now"),'yyMMddHHmmss')));
mkdir(compile_dir);

% Clean from MATLAB path every reference to SPM and subfolders
% This reduces compilation time and the output file size
% MATLAB path will be restored at the end of the script
spm_dir = spm('dir');
split_path = split(oldpath,';'); %to keep the char format
%split_path = split(convertCharsToStrings(oldpath),';'); %changes to string format
keep_path = ~contains(split_path,strcat(filesep,'spm'));
new_path = split_path(keep_path);
new_path = join(new_path',';');
path(new_path{1});
addpath(spm_dir);
addpath(get_path('cat12_dir'));

% If Contents.txt doesn't exist in <spm_dir>, run the following 2 lines:
%sts = copyfile(fullfile(spm('Dir'),'Contents.m'),fullfile(spm('Dir'),'Contents.txt'));
%if ~sts, warning('Copy of Contents.m failed.'); end

mcc('-m', 'run_segment_gm.m','-C', '-v',...
    '-o', 'SegmentGM',...
    '-d', compile_dir,...
    '-R', '-logfile,output.txt',...
    '-R', '-startmsg,[INFO]Starting application, please wait...',...
    '-N', ...
    '-p',fullfile(matlabroot,'toolbox','signal'),...
    '-a', fullfile(spm('dir'),'Contents.txt'),...
    '-a', fullfile(spm('dir'),'tpm'),...
    '-a', fullfile(spm('dir'),'toolbox','Shoot'),...
    '-a', fullfile(spm('dir'),'toolbox','OldNorm'),...
    '-a', fullfile(get_path('cat12_dir'),'Contents.txt'),...
    '-a', fullfile(get_path('cat12_dir'),'*.m'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_1.50mm','Template_*_IXI555_MNI152_GS.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','T1.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','cat_1mm.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','cat.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','brainmask.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','Template*GS.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','Template_T1*.nii'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym','cat_bloodvessels.nii'),...
    '-a', fullfile(pwd,'utils'));

% Copy the cat12 modules for preprocessing
% You can change some parameters of that module after compilation, for example, the number of
% pre-processing threads
sts = copyfile(fullfile('.','cat12_modules'), fullfile(compile_dir,'cat12_modules'));
if ~sts, warning('[WARNING]Copy of cat12_modules directory failed.'); end

sts = copyfile(fullfile('.','7zip'), fullfile(compile_dir,'7zip'));
if ~sts, warning('[WARNING]Copy of 7zip directory failed.'); end

path(oldpath);
fprintf('\n[INFO]Elapsed time %.2f minutes\n', double(toc/60));
fprintf('[INFO]Compilation done!\n');